name: Generate SDK

on: 
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '14'

            - name: Set up Dotnet 6
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: '6.0.x'
                source-url: https://nuget.pkg.github.com/mydatamyconsent/index.json
              env:
                NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  java-version: '15'
                  distribution: 'adopt'

            - name: Install OpenAPI Tools
              run: |
                  npm install @openapitools/openapi-generator-cli -g

            - name: Cleanup folders
              run: |
                rm -rf ./src
                rm -rf ./docs

            - name: Generate SDK's
              run: |
                  npx @openapitools/openapi-generator-cli generate

            - run: dotnet build src/MyDataMyConsent.Sdk/MyDataMyConsent.Sdk.csproj
            
            - name: Create the package
              run: dotnet pack --configuration Release src/MyDataMyConsent.Sdk/MyDataMyConsent.Sdk.csproj

            - uses: actions/delete-package-versions@v3
              with:
                package-name: 'MyDataMyConsent.Sdk'
                num-old-versions-to-delete: 1
            
            - name: Publish the package to Github Package Registry
              run: dotnet nuget push src/MyDataMyConsent.Sdk/bin/Release/*.nupkg

            - name: Repository update
              uses: EndBug/add-and-commit@v8
              with:
                  author_name: Balamurali Pandranki
                  author_email: balamurali@live.com
                  default_author: github_actor
                  message: 'Generate API SDK'
                  push: true